export const UPDATE_MOMENT = 'UPDATE MOMENT';
export const FETCH_SCHEDULED_RECIPES_FOR_DAY_REQUEST = 'FETCH_SCHEDULED_RECIPES_FOR_DAY_REQUEST';
export const FETCH_SCHEDULED_RECIPES_FOR_DAY_SUCCESS = 'FETCH_SCHEDULED_RECIPES_FOR_DAY_SUCCESS';
export const FETCH_SCHEDULED_RECIPES_FOR_DAY_FAILURE = 'FETCH_SCHEDULED_RECIPES_FOR_DAY_FAILURE';
export const OPEN_ADD_RECIPES_MODAL = 'OPEN_ADD_RECIPES_MODAL';
export const CLOSE_ADD_RECIPES_MODAL = 'CLOSE_ADD_RECIPES_MODAL';
