export const UPDATE_MOMENT = 'UPDATE MOMENT';
export const FETCH_SCHEDULED_RECIPES_FOR_DAY_REQUEST = 'FETCH_SCHEDULED_RECIPES_FOR_DAY_REQUEST';
export const FETCH_SCHEDULED_RECIPES_FOR_DAY_SUCCESS = 'FETCH_SCHEDULED_RECIPES_FOR_DAY_SUCCESS';
export const FETCH_SCHEDULED_RECIPES_FOR_DAY_FAILURE = 'FETCH_SCHEDULED_RECIPES_FOR_DAY_FAILURE';
